//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGTE_V1._8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Passageiro_Viagem
    {
        public Tbl_Passageiro_Viagem()
        {
            this.Tbl_Viagem1 = new HashSet<Tbl_Viagem>();
        }
    
        public int ID { get; set; }
        public string Passageiros { get; set; }
        public string Obs_Viagem { get; set; }
        public Nullable<int> Viagem_ID { get; set; }
        public Nullable<int> Aluno_ID { get; set; }
    
        public virtual Tbl_Aluno Tbl_Aluno { get; set; }
        public virtual Tbl_Viagem Tbl_Viagem { get; set; }
        public virtual ICollection<Tbl_Viagem> Tbl_Viagem1 { get; set; }
    }
}
