//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGTE_V1._8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Viagem
    {
        public Tbl_Viagem()
        {
            this.Tbl_Endereco = new HashSet<Tbl_Endereco>();
            this.Tbl_Hora_Viagem = new HashSet<Tbl_Hora_Viagem>();
            this.Tbl_Passageiro_Viagem = new HashSet<Tbl_Passageiro_Viagem>();
        }
    
        public int ID { get; set; }
        public string Motorista { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
        public string Obs_Viagem { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> Aluno_ID { get; set; }
        public Nullable<int> Escola_ID { get; set; }
        public Nullable<int> Veiculo_ID { get; set; }
        public Nullable<int> Motorista_ID { get; set; }
        public Nullable<int> Passageiro_ID { get; set; }
    
        public virtual Tbl_Aluno Tbl_Aluno { get; set; }
        public virtual ICollection<Tbl_Endereco> Tbl_Endereco { get; set; }
        public virtual Tbl_Escola Tbl_Escola { get; set; }
        public virtual ICollection<Tbl_Hora_Viagem> Tbl_Hora_Viagem { get; set; }
        public virtual Tbl_Motorista Tbl_Motorista { get; set; }
        public virtual ICollection<Tbl_Passageiro_Viagem> Tbl_Passageiro_Viagem { get; set; }
        public virtual Tbl_Passageiro_Viagem Tbl_Passageiro_Viagem1 { get; set; }
        public virtual Tbl_Veiculo Tbl_Veiculo { get; set; }
    }
}
