//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGTE_V1._8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Aluno
    {
        public Tbl_Aluno()
        {
            this.Tbl_Endereco = new HashSet<Tbl_Endereco>();
            this.Tbl_Hora_Viagem = new HashSet<Tbl_Hora_Viagem>();
            this.Tbl_Passageiro_Viagem = new HashSet<Tbl_Passageiro_Viagem>();
            this.Tbl_Viagem = new HashSet<Tbl_Viagem>();
        }
    
        public int ID { get; set; }
        public string Nome { get; set; }
        public string RG { get; set; }
        public string Escola { get; set; }
        public string Cidade { get; set; }
        public string Bairro { get; set; }
        public string CEP { get; set; }
        public string Estado { get; set; }
        public string Endereco_1 { get; set; }
        public string Endereco_2 { get; set; }
        public Nullable<int> Ativo { get; set; }
        public Nullable<int> Cliente_ID { get; set; }
        public Nullable<int> Veiculo_ID { get; set; }
        public Nullable<int> Escola_ID { get; set; }
    
        public virtual Tbl_Cliente Tbl_Cliente { get; set; }
        public virtual Tbl_Escola Tbl_Escola { get; set; }
        public virtual Tbl_Veiculo Tbl_Veiculo { get; set; }
        public virtual ICollection<Tbl_Endereco> Tbl_Endereco { get; set; }
        public virtual ICollection<Tbl_Hora_Viagem> Tbl_Hora_Viagem { get; set; }
        public virtual ICollection<Tbl_Passageiro_Viagem> Tbl_Passageiro_Viagem { get; set; }
        public virtual ICollection<Tbl_Viagem> Tbl_Viagem { get; set; }
    }
}
