//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
//teste
namespace SGTE_V1._8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Veiculo : Tbl_Aluno
    {
        Tbl_Aluno aluno = new Tbl_Aluno();
        public Tbl_Veiculo()
        {
            this.Tbl_Aluno = new HashSet<Tbl_Aluno>();
            this.Tbl_Motorista = new HashSet<Tbl_Motorista>();
            this.Tbl_Veiculo1 = new HashSet<Tbl_Veiculo>();
            this.Tbl_Viagem = new HashSet<Tbl_Viagem>();
        }
    
        public int ID { get; set; }
        public int Cod_Veiculo { get; set; }
        public string Placa { get; set; }
        public string Modelo { get; set; }
        public string Renavam { get; set; }
        public string Cidade { get; set; }
        public string Licenca { get; set; }
        public string Chassi { get; set; }
        public string Ano_Fabricacao { get; set; }
        public int Num_Lugares { get; set; }
        public int Lugares_Vagos { get; set; }
        public string UF { get; set; }
        public Nullable<int> Ativo { get; set; }
        public string Status { get; set; }
        public Nullable<int> Escola_ID { get; set; }
        public Nullable<int> Motorista_ID { get; set; }
    
        public virtual ICollection<Tbl_Aluno> Tbl_Aluno { get; set; }
        public virtual Tbl_Escola Tbl_Escola { get; set; }
        public virtual ICollection<Tbl_Motorista> Tbl_Motorista { get; set; }
        public virtual ICollection<Tbl_Veiculo> Tbl_Veiculo1 { get; set; }
        public virtual Tbl_Veiculo Tbl_Veiculo2 { get; set; }
        public virtual ICollection<Tbl_Viagem> Tbl_Viagem { get; set; }


        public List<Tbl_Aluno> listarAlunos()   
        {
            List<Tbl_Aluno> lista = new List<Tbl_Aluno>();
            SGTE2Entities db = new SGTE2Entities();
            Tbl_Veiculo veiculo = new Tbl_Veiculo();
            var consulta = db.stp_RelacaoAlunoVeiculo(veiculo.ID);

            foreach (var aluno in consulta)
            {
                Tbl_Aluno a = new Tbl_Aluno();
                Tbl_Veiculo b = new Tbl_Veiculo();

                a.Nome = aluno.Nome;
                a.RG = aluno.RG;
                a.Escola = aluno.Escola;
                a.Cidade = aluno.Cidade;
                a.Bairro = aluno.Bairro;
                a.CEP = aluno.CEP;
                a.Estado = aluno.Estado;
                a.Endereco_1 = aluno.Endereco_1;
                a.Endereco_2 = aluno.Endereco_2;
                //a.ativo = aluno.Ativo;


                lista.Add(a);

            }

            return lista;
        }

    }
}
