//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGTE_V1._8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Login
    {
        public int ID { get; set; }
        public string Login { get; set; }
        public string Senha { get; set; }
        public Nullable<int> Nivel_Acesso { get; set; }
        public Nullable<int> Cliente_ID { get; set; }
        public Nullable<int> Funcionario_ID { get; set; }
    
        public virtual Tbl_Cliente Tbl_Cliente { get; set; }
        public virtual Tbl_Funcionario Tbl_Funcionario { get; set; }
    }
}
