//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGTE_V1._8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Escola
    {
        public Tbl_Escola()
        {
            this.Tbl_Aluno = new HashSet<Tbl_Aluno>();
            this.Tbl_Veiculo = new HashSet<Tbl_Veiculo>();
            this.Tbl_Viagem = new HashSet<Tbl_Viagem>();
        }
    
        public int ID { get; set; }
        public string Nome { get; set; }
        public string Endereco { get; set; }
        public string Cidade { get; set; }
        public string Bairro { get; set; }
        public string CEP { get; set; }
        public string Estado { get; set; }
        public string CNPJ { get; set; }
        public Nullable<int> Ativo { get; set; }
    
        public virtual ICollection<Tbl_Aluno> Tbl_Aluno { get; set; }
        public virtual ICollection<Tbl_Veiculo> Tbl_Veiculo { get; set; }
        public virtual ICollection<Tbl_Viagem> Tbl_Viagem { get; set; }
    }
}
